### PR TITLE
Match monthly prices with vag

### PR DESCRIPTION
**Pull request by thomasdouenne**

### CODE REVIEW

**Comment by benjello** [comment]
I think that matching prices with vag sould not be done in this package but in omepfisca-france-indirect-taxation

**Comment by benjello** [comment]
@thomasdouenne : what should I do it hthis PR ?

**Comment by benjello** [comment]
Please confirm @thomasdouenne

**Comment by thomasdouenne** [comment]
Yes you can merge this PR

**Comment by benjello** [comment]
Done by hand

**Pull request closed without merging**
